{% set version = "0.1.1" %}

package:
  name: radsex
  version: {{ version }}

source:
  url: https://github.com/RomainFeron/RadSex/archive/v{{ version }}.tar.gz
  sha256: 0b240be5ed9b3ff64e9f3af2e8dd093f4797ed42593081c2d5a1fee4dfc619e1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - bin/radsex 2>&1'

about:
  home: https://github.com/RomainFeron/RadSex
  license: GPLv3
  license_file: LICENSE
  summary: 'A pipeline to find and visualize sex signal in RAD-Seq data'
